# -*- coding: utf-8 -*-
"""Aula 1 comandos básicos em python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8dxPu55ziOlY7_MxvjJMYtjrWoey1Ex
"""

print ("Quanto tempo não te vejo, tudo bem?!")

"""**int** é uma comando para manter os valores inteiros

**float** é em casa decimal

"texto" = STR - Strung

4,5 cHoco
5,5 coxinha
7 suco

"""

p_suco= 6.50
p_coxinha= 5.50
p_chocolate= 4.50

print ("Boa tarde senhor, vi que você adorou nossas opções")
coxinhas=int(input("Quantas coxinhas você comeu? "))
sucos=int(input("e quantos copos de sucos você bebeu? "))
chocolates=int(input("quantos suflairs você comprou? "))
conta=(p_suco*sucos)+(p_coxinha*coxinhas)+(p_chocolate*chocolates)

print ("Que ótimo! então sua conta vai ficar,",coxinhas, "coxinhas" ,sucos, "copos de suco e",chocolates, "suflairs. Sua conta ficou, R$",conta,)