# -*- coding: utf-8 -*-
"""Exercícios LE08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVqlI4OcSC4E-eI6Qw8b2XMjbSbW8Ypt

INíCIO DO EXERCÍCIO 07: Calculo de média
"""

print ("Olá, vamos calcular a sua média final") #Introdução Bonitinha

n1= float(input("Informe-me a nota de sua primeira prova\n")) #Região de coleta das variáveis
print ("Anotado...")

n2= float(input("Informe-me a nota de sua segunda prova\n"))
print ("Anotado...")

n3= float(input("Informe-me a nota de sua terceira prova\n"))
print ("Anotado...")

n4= float(input("Informe-me a nota de sua quarta prova\n"))
print ("Anotado e calculando a média aritmética")


print("Sua média final será:")
print((n1+n2+n3+n4)/4) #Fórmula p/calculo da média

"""INíCIO DO EXERCÍCIO 08: Criação de IMC"""

print("Oi, tudo bem? vamos calcular o seu Indice de Massa Corporal")

Peso=float(input("Qual é o seu peso atual em KG?\n")) #lembre-se de usar . no lugar da ,

print("Certo")

Altura=float(input("Qual é sua altura em metros?\n"))

print("Perfeito, apenas com esses dois dados já podemos calcular seu IMC")


print("Seu IMC é:")
print(Peso/(Altura*Altura)) #Ele não estava lendo ^2, substitui por Altura*Altura

"""INíCIO DO EXERCÍCIO 09: Leitura de Idade"""

]print ("Vamos demonstrar quantos dias de vida você tem")

print ("informe sua idade\n")
anos=int(input("em anos:"))
meses=int(input("em meses: "))
dias=int(input("em dias: "))
print("Você tem ", anos*365+meses*30+dias,"dias de vida ")