# -*- coding: utf-8 -*-
"""Exercícios LE09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iixeToxJoehwqGc2uH89mffDPNsVgTbC

Exercício 4 - Calculos com quadrado e cubo
"""

print ("Olá, tudo bem? vamos demonstrar qual é o quadrado e o cubo de seu número!")

Numero = float(input("Me de um número\n"))  #Coleta o número de nosso usuário.

#Calculos
print ("Que número legal, o quadrado deste número é:",Numero**2)

print ("Este número ao cubo é",(Numero**3)) # Podemos utilizar ** para potências

"""Exercício 5 - Mudança de graus Celsius P/Farenheit e P/Kelvin


"""

print ("Olá, como vai? Você sabe representar uma temperatura de Celsius para Farenheit ou para Kelvin?\nEu posso te ajudar com isso!")
Temp_C= float(input("Me de uma temperatura em Celsius: \n")) #Coleta da temperatura em Celsius

print ("Essa temperatura será",(1.8*Temp_C)+32,"Farenheit") #Estava com dificuldades para criar um código que dividisse, então dividi 9/5 e coloquei 1.8 multiplicando
print ("e essa temperatura será",Temp_C+273,"Kelvin")

"""Exercício 6 - Padaria Sopão



"""

#Valores fixos
P=0.80  #Preço do Pãozinho
B=2.50  #Preço da Broa
Euro=4.60

#Coleta dos dados
Pao= int(input("Quantos pães foram vendidos hoje, Sr. João?\n"))
Broa= int(input("Quantas broas foram vendidas hoje?\n"))

total_arrecadado=(Pao*P)+(Broa*B) #Total das vendas
print("O total de vendas do dia de hoje foi de: R$",total_arrecadado,)

#Com isso, sabemos que 43% desse valor vai para os custos de fabricação
custo=(total_arrecadado*0.43)

#Do restante 15% são guardados e 15% são convertidos para euro

poupanca=(total_arrecadado-custo)*0.15 #Total arrecadado - o custo vai me dar a sobra, essa sobra 15% vai para a poupança
euros=(poupanca/Euro) # a outra sobra vai para a compra de euros se 1 euro = 4,60. Poupança/Euro = Valor de euros comprados

print("Desse valor o senhor deve destribuir:")
print("Para pagar os custos: R$",custo)
print("Para a poupança: R$",poupanca)
print("E para a compra de euros, podem ser comprados",euros,"euros")